### ISSUE TITLE
uTP connection not detected as having been closed

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#405]
While running crust_peer on Ubuntu 15.10, if two instances form a uTP connection and one peer is then stopped, the other peer doesn't report the connection as having been broken.  I left the remaining instance to run for over 20 minutes after killing the peer, and on running `list` the dead peer still shows up as connected.

**Comment by vinipsmaker** [comment]
Actually I'm having this issue with `TCP` as well. I might very well be just an issue with `crust_peer`. I'll take a deeper look now.

**Comment by vinipsmaker** [comment]
Sorry, I've been mislead by the fact that connections aren't automatically removed from the list (must call `clean` on the CLI).

**Comment by vinipsmaker** [comment]
After changing `crust_peer` to listen on `uTP`, here are my findings:

- Connect has dropped (`Lost connection to peer at Connection(Utp V4(0.0.0.0:58660) -> V4(127.0.0.1:56194))`) much much sooner than your 20 minutes. I guess the error you initially mentioned was related to issues fixed in `temp_utp` 0.7.0.
- Connection loss is not detect as fast as TCP. I believe the main thread closes before the uTP thread has a chance to send the `fin` packet. I'll investigate this problem.

**Comment by madadam** [comment]
I need help with reproducing this issue. I'm bit confused about how to use crust_peer. When I run two instances, they automatically connect using TCP. How to I connect them using uTP?

On the other hand, if this issue is caused by UtpWrapper's thread not being joined, then that should be easy to fix. But I need some way to verify that the fix works.

**Comment by madadam** [comment]
Ok, figured out how to reproduce the issue. Joining the UtpWrapper thread does not fix it though :(. My guess is that when the instance is killed forcefully, the destructors are not run, so no `fin` packet is sent. Going to investigate this a bit more to figure out the best way to fix it.

**Comment by madadam** [comment]
Ok, so after a bit of playing with this, these are my observations:

- The uTP connection is dropped eventually, it just takes much more time than in the TCP case
- Joining the UtpWrapper thread on drop does not have any effect on the above

So I'm not sure there actually is a bug? I can push the UtpWrapper thread joining, which is something we should be doing anyway (it's not nice to keep hanging threads around), but otherwise not sure what else can be done.

**Comment by madadam** [comment]
Should be fixed by #466.

**Comment by vinipsmaker** [comment]
Yes, it should be fixed. Can you try again, @Fraser999?

**Comment by Fraser999** [comment]
I'll close this as due to the heavy refactoring going on plus the suspected fix anyway, I expect this report is no longer valid.
